<?php

/**
 * @file
 * Contains hook definitions and main entry point for ERPAL platform module.
 */

/**
 * Implements hook_homebox().
 */
function erpal_platform_core_homebox() {
  module_load_include('inc', 'erpal_platform_core', 'includes/homebox.default');
  return _erpal_platform_core_homebox_defaults();
}

/**
 * Implements hook_permission().
 */
function erpal_platform_core_permission() {
  return array(
    'view erpal debug output' => array(
      'title' => t('View ERPAL Platform debug info'),
      'description' => t('Provides access to debug data from ERPAL Platform modules.'),
    ),
  );
}

/**
 * Implements hook_entity_insert().
 */
function erpal_platform_core_entity_insert($entity, $type) {
  // Show debug message when entity has been created.
  if (!drupal_installation_attempted() && user_access('view erpal debug output')) {
    $info = entity_get_info($type);
    $url = entity_uri($type, $entity);
    $label = entity_label($type, $entity);
    if (!empty($url['path']) && !empty($label) && !empty($info['bundle keys']) && !empty($entity->{$info['bundle keys']['bundle']})) {
      $bundle = $entity->{$info['bundle keys']['bundle']};
      $bundle_label = $info['bundles'][$bundle]['label'];

      drupal_set_message(t('@type has been created (<a href="@url">@title</a>).', array('@url' => url($url['path']), '@type' => $bundle_label, '@title' => $label)));
    }
  }
}
