<?php

/**
 * @file
 * Code for the Erpal Layout.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function erpal_layout_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function erpal_layout_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  if ($module == "panels" && $api == "layouts") {
    return array("version" => "1");
  }
  if ($module == 'panels_mini' && $api == 'panels_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_default_page_manager_handlers().
 */
function erpal_layout_default_page_manager_handlers() {
  $export = array();

  $handler = new stdClass();
  $handler->disabled = FALSE; /* Edit this to true to make a default handler disabled initially */
  $handler->api_version = 1;
  $handler->name = 'site_template_panel_context';
  $handler->task = 'site_template';
  $handler->subtask = '';
  $handler->handler = 'panel_context';
  $handler->weight = 0;
  $handler->conf = array(
    'title' => 'ERPAL default',
    'no_blocks' => 1,
    'pipeline' => 'standard',
    'body_classes_to_remove' => '',
    'body_classes_to_add' => '',
    'css_id' => '',
    'css' => '',
    'contexts' => array(),
    'relationships' => array(),
    'access' => array(
      'plugins' => array(
        0 => array(
          'name' => 'theme',
          'settings' => array(
            'theme' => 'erpal_theme',
          ),
          'not' => FALSE,
        ),
      ),
      'logic' => 'and',
    ),
  );
  $display = new panels_display();
  $display->layout = 'erpalsitetemplate';
  $display->layout_settings = array();
  $display->panel_settings = array(
    'style_settings' => array(
      'default' => NULL,
      'top' => NULL,
      'left' => NULL,
      'right' => NULL,
      'bottom' => NULL,
      'righttabs' => NULL,
      'page-header-left' => NULL,
      'page-header-right' => NULL,
    ),
  );
  $display->cache = array();
  $display->title = '';
  $display->uuid = '3854b10e-0fba-4f76-a395-539ed1ab4321';
  $display->content = array();
  $display->panels = array();
  $pane = new stdClass();
  $pane->pid = 'new-6c6f0e47-777e-4c4c-968a-8193f9457c94';
  $pane->panel = 'bottom';
  $pane->type = 'powered_by';
  $pane->subtype = 'powered_by';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'types' => array(),
    'field_name' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = '6c6f0e47-777e-4c4c-968a-8193f9457c94';
  $display->content['new-6c6f0e47-777e-4c4c-968a-8193f9457c94'] = $pane;
  $display->panels['bottom'][0] = 'new-6c6f0e47-777e-4c4c-968a-8193f9457c94';
  $pane = new stdClass();
  $pane->pid = 'new-bf44ebdd-7f82-4db8-8b33-eecd5e00c089';
  $pane->panel = 'left';
  $pane->type = 'block';
  $pane->subtype = 'menu-erpal-menu';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'override_title' => 1,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = 'bf44ebdd-7f82-4db8-8b33-eecd5e00c089';
  $display->content['new-bf44ebdd-7f82-4db8-8b33-eecd5e00c089'] = $pane;
  $display->panels['left'][0] = 'new-bf44ebdd-7f82-4db8-8b33-eecd5e00c089';
  $pane = new stdClass();
  $pane->pid = 'new-096541d5-c302-4c35-b813-399a66ab501a';
  $pane->panel = 'page-header-left';
  $pane->type = 'page_logo';
  $pane->subtype = 'page_logo';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array();
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = '096541d5-c302-4c35-b813-399a66ab501a';
  $display->content['new-096541d5-c302-4c35-b813-399a66ab501a'] = $pane;
  $display->panels['page-header-left'][0] = 'new-096541d5-c302-4c35-b813-399a66ab501a';
  $pane = new stdClass();
  $pane->pid = 'new-b893103e-a6cb-483e-9235-f7f324edf680';
  $pane->panel = 'page-header-left';
  $pane->type = 'page_site_name';
  $pane->subtype = 'page_site_name';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array();
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 1;
  $pane->locks = array();
  $pane->uuid = 'b893103e-a6cb-483e-9235-f7f324edf680';
  $display->content['new-b893103e-a6cb-483e-9235-f7f324edf680'] = $pane;
  $display->panels['page-header-left'][1] = 'new-b893103e-a6cb-483e-9235-f7f324edf680';
  $pane = new stdClass();
  $pane->pid = 'new-e6de1b56-d3b6-4ce5-9ff3-307e6110cb1b';
  $pane->panel = 'page-header-right';
  $pane->type = 'panels_mini';
  $pane->subtype = 'erpal_dropdown_user_menu';
  $pane->shown = TRUE;
  $pane->access = array(
    'plugins' => array(
      0 => array(
        'name' => 'role',
        'settings' => array(
          'rids' => array(
            0 => 2,
          ),
        ),
        'context' => 'logged-in-user',
        'not' => FALSE,
      ),
    ),
  );
  $pane->configuration = array(
    'override_title' => 1,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = 'e6de1b56-d3b6-4ce5-9ff3-307e6110cb1b';
  $display->content['new-e6de1b56-d3b6-4ce5-9ff3-307e6110cb1b'] = $pane;
  $display->panels['page-header-right'][0] = 'new-e6de1b56-d3b6-4ce5-9ff3-307e6110cb1b';
  $pane = new stdClass();
  $pane->pid = 'new-c76e38a0-5bbb-4e51-8b4c-bc0f39d4f7fb';
  $pane->panel = 'page-header-right';
  $pane->type = 'panels_mini';
  $pane->subtype = 'erpal_anonymous_user_panel';
  $pane->shown = TRUE;
  $pane->access = array(
    'plugins' => array(
      0 => array(
        'name' => 'role',
        'settings' => array(
          'rids' => array(
            0 => 1,
          ),
        ),
        'context' => 'logged-in-user',
        'not' => FALSE,
      ),
    ),
  );
  $pane->configuration = array(
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 1;
  $pane->locks = array();
  $pane->uuid = 'c76e38a0-5bbb-4e51-8b4c-bc0f39d4f7fb';
  $display->content['new-c76e38a0-5bbb-4e51-8b4c-bc0f39d4f7fb'] = $pane;
  $display->panels['page-header-right'][1] = 'new-c76e38a0-5bbb-4e51-8b4c-bc0f39d4f7fb';
  $pane = new stdClass();
  $pane->pid = 'new-eb400803-4724-4a8f-8d64-cca2eb9a3ccf';
  $pane->panel = 'right';
  $pane->type = 'page_title';
  $pane->subtype = 'page_title';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'markup' => 'h1',
    'class' => '',
    'id' => '',
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = 'eb400803-4724-4a8f-8d64-cca2eb9a3ccf';
  $display->content['new-eb400803-4724-4a8f-8d64-cca2eb9a3ccf'] = $pane;
  $display->panels['right'][0] = 'new-eb400803-4724-4a8f-8d64-cca2eb9a3ccf';
  $pane = new stdClass();
  $pane->pid = 'new-8bb5efef-a892-4216-9c47-8d8290b4a63d';
  $pane->panel = 'right';
  $pane->type = 'page_breadcrumb';
  $pane->subtype = 'page_breadcrumb';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array();
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 1;
  $pane->locks = array();
  $pane->uuid = '8bb5efef-a892-4216-9c47-8d8290b4a63d';
  $display->content['new-8bb5efef-a892-4216-9c47-8d8290b4a63d'] = $pane;
  $display->panels['right'][1] = 'new-8bb5efef-a892-4216-9c47-8d8290b4a63d';
  $pane = new stdClass();
  $pane->pid = 'new-fc749562-787b-4fc7-9de0-52e4cd994c99';
  $pane->panel = 'right';
  $pane->type = 'page_messages';
  $pane->subtype = 'page_messages';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array();
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 2;
  $pane->locks = array();
  $pane->uuid = 'fc749562-787b-4fc7-9de0-52e4cd994c99';
  $display->content['new-fc749562-787b-4fc7-9de0-52e4cd994c99'] = $pane;
  $display->panels['right'][2] = 'new-fc749562-787b-4fc7-9de0-52e4cd994c99';
  $pane = new stdClass();
  $pane->pid = 'new-70ce4aba-f141-4439-b17f-101f99fd6eda';
  $pane->panel = 'right';
  $pane->type = 'block';
  $pane->subtype = 'system-help';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 3;
  $pane->locks = array();
  $pane->uuid = '70ce4aba-f141-4439-b17f-101f99fd6eda';
  $display->content['new-70ce4aba-f141-4439-b17f-101f99fd6eda'] = $pane;
  $display->panels['right'][3] = 'new-70ce4aba-f141-4439-b17f-101f99fd6eda';
  $pane = new stdClass();
  $pane->pid = 'new-2afe3fab-96f2-401b-be3b-f06439833880';
  $pane->panel = 'right';
  $pane->type = 'page_actions';
  $pane->subtype = 'page_actions';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array();
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 4;
  $pane->locks = array();
  $pane->uuid = '2afe3fab-96f2-401b-be3b-f06439833880';
  $display->content['new-2afe3fab-96f2-401b-be3b-f06439833880'] = $pane;
  $display->panels['right'][4] = 'new-2afe3fab-96f2-401b-be3b-f06439833880';
  $pane = new stdClass();
  $pane->pid = 'new-2e487454-10c6-4d97-b0fc-6b783caeb1b4';
  $pane->panel = 'right';
  $pane->type = 'page_content';
  $pane->subtype = 'page_content';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'context' => 'argument_page_content_1',
    'override_title' => 1,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 5;
  $pane->locks = array();
  $pane->uuid = '2e487454-10c6-4d97-b0fc-6b783caeb1b4';
  $display->content['new-2e487454-10c6-4d97-b0fc-6b783caeb1b4'] = $pane;
  $display->panels['right'][5] = 'new-2e487454-10c6-4d97-b0fc-6b783caeb1b4';
  $pane = new stdClass();
  $pane->pid = 'new-6c70aeca-92eb-4936-aeef-66eaae2774ac';
  $pane->panel = 'righttabs';
  $pane->type = 'page_tabs';
  $pane->subtype = 'page_tabs';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'type' => 'both',
    'id' => 'tabs',
    'override_title' => 1,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = '6c70aeca-92eb-4936-aeef-66eaae2774ac';
  $display->content['new-6c70aeca-92eb-4936-aeef-66eaae2774ac'] = $pane;
  $display->panels['righttabs'][0] = 'new-6c70aeca-92eb-4936-aeef-66eaae2774ac';
  $display->hide_title = PANELS_TITLE_FIXED;
  $display->title_pane = '0';
  $handler->conf['display'] = $display;

  $export['site_template_panel_context'] = $handler;

  return $export;
}

/**
 * Implements hook_default_panels_mini().
 */
function erpal_layout_default_panels_mini() {
  $export = array();

  /* dropdown user menu */
  $mini = new stdClass();
  $mini->disabled = FALSE; /* Edit this to true to make a default mini disabled initially */
  $mini->api_version = 1;
  $mini->name = 'erpal_dropdown_user_menu';
  $mini->category = '';
  $mini->admin_title = 'ERPAL dropdown user menu';
  $mini->admin_description = '';
  $mini->requiredcontexts = array();
  $mini->contexts = array(
    0 => array(
      'identifier' => 'User',
      'keyword' => 'user',
      'name' => 'user',
      'type' => 'current',
      'uid' => '',
      'id' => 1,
    ),
  );
  $mini->relationships = array();
  $display = new panels_display();
  $display->layout = 'erpaldropdownregion';
  $display->layout_settings = array();
  $display->panel_settings = array(
    'style_settings' => array(
      'default' => NULL,
      'center' => NULL,
      'trigger' => NULL,
      'dropdown' => NULL,
    ),
  );
  $display->cache = array();
  $display->title = '';
  $display->uuid = 'cd279c8f-4241-4ca1-b002-f94d7504d188';
  $display->content = array();
  $display->panels = array();
  $pane = new stdClass();
  $pane->pid = 'new-a906d76c-53ce-49df-8727-a06c6b205463';
  $pane->panel = 'dropdown';
  $pane->type = 'user_menu_welcome';
  $pane->subtype = 'user_menu_welcome';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'greeting' => 'Hey',
    'context' => 'context_user_1',
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = 'a906d76c-53ce-49df-8727-a06c6b205463';
  $display->content['new-a906d76c-53ce-49df-8727-a06c6b205463'] = $pane;
  $display->panels['dropdown'][0] = 'new-a906d76c-53ce-49df-8727-a06c6b205463';
  $pane = new stdClass();
  $pane->pid = 'new-77fc4a8f-aab6-4801-9fa6-389446ead170';
  $pane->panel = 'dropdown';
  $pane->type = 'block';
  $pane->subtype = 'system-user-menu';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'override_title' => 1,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 1;
  $pane->locks = array();
  $pane->uuid = '77fc4a8f-aab6-4801-9fa6-389446ead170';
  $display->content['new-77fc4a8f-aab6-4801-9fa6-389446ead170'] = $pane;
  $display->panels['dropdown'][1] = 'new-77fc4a8f-aab6-4801-9fa6-389446ead170';
  $pane = new stdClass();
  $pane->pid = 'new-263469a9-64e5-4e0a-87d1-d5f59d8801f1';
  $pane->panel = 'trigger';
  $pane->type = 'user_avatar';
  $pane->subtype = 'user_avatar';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'image_style' => 'usermenu_profileimage',
    'context' => 'context_user_1',
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = '263469a9-64e5-4e0a-87d1-d5f59d8801f1';
  $display->content['new-263469a9-64e5-4e0a-87d1-d5f59d8801f1'] = $pane;
  $display->panels['trigger'][0] = 'new-263469a9-64e5-4e0a-87d1-d5f59d8801f1';
  $display->hide_title = PANELS_TITLE_FIXED;
  $display->title_pane = 'new-77fc4a8f-aab6-4801-9fa6-389446ead170';
  $mini->display = $display;

  $export['profile_details'] = $mini;


  /* contacts merged tab for invoice, order & quote */
  $mini = new stdClass();
  $mini->disabled = FALSE; /* Edit this to true to make a default mini disabled initially */
  $mini->api_version = 1;
  $mini->name = 'erpal_contact_view_merged_tab';
  $mini->category = 'Mini panels';
  $mini->admin_title = 'ERPAL contact view merged tab';
  $mini->admin_description = '';
  $mini->requiredcontexts = array(
    0 => array(
      'identifier' => 'CRM Core Contact',
      'keyword' => 'crm_core_contact',
      'name' => 'entity:crm_core_contact',
      'entity_id' => '',
      'id' => 1,
    ),
  );
  $mini->contexts = array();
  $mini->relationships = array();
  $display = new panels_display();
  $display->layout = 'naked';
  $display->layout_settings = array();
  $display->panel_settings = array(
    'style_settings' => array(
      'default' => NULL,
      'content' => NULL,
    ),
  );
  $display->cache = array();
  $display->title = '';
  $display->uuid = '9bb1aabc-64a0-4072-bda0-da7b297f9120';
  $display->content = array();
  $display->panels = array();
  $pane = new stdClass();
  $pane->pid = 'new-0eb1802a-9dce-47dd-b1f2-622c4d23f2ff';
  $pane->panel = 'content';
  $pane->type = 'views_panes';
  $pane->subtype = 'erpal_quote-panel_pane_3';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'context' => array(
      0 => 'requiredcontext_entity:crm_core_contact_1',
    ),
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = '0eb1802a-9dce-47dd-b1f2-622c4d23f2ff';
  $display->content['new-0eb1802a-9dce-47dd-b1f2-622c4d23f2ff'] = $pane;
  $display->panels['content'][0] = 'new-0eb1802a-9dce-47dd-b1f2-622c4d23f2ff';
  $pane = new stdClass();
  $pane->pid = 'new-857684ec-44fc-4bf5-b1dd-57f843ff13d3';
  $pane->panel = 'content';
  $pane->type = 'views_panes';
  $pane->subtype = 'erpal_order-panel_pane_3';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'context' => array(
      0 => 'requiredcontext_entity:crm_core_contact_1',
    ),
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 1;
  $pane->locks = array();
  $pane->uuid = '857684ec-44fc-4bf5-b1dd-57f843ff13d3';
  $display->content['new-857684ec-44fc-4bf5-b1dd-57f843ff13d3'] = $pane;
  $display->panels['content'][1] = 'new-857684ec-44fc-4bf5-b1dd-57f843ff13d3';
  $pane = new stdClass();
  $pane->pid = 'new-16593066-e539-4170-a9df-96278861a538';
  $pane->panel = 'content';
  $pane->type = 'views_panes';
  $pane->subtype = 'erpal_invoice-panel_pane_1';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'context' => array(
      0 => 'requiredcontext_entity:crm_core_contact_1',
    ),
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 2;
  $pane->locks = array();
  $pane->uuid = '16593066-e539-4170-a9df-96278861a538';
  $display->content['new-16593066-e539-4170-a9df-96278861a538'] = $pane;
  $display->panels['content'][2] = 'new-16593066-e539-4170-a9df-96278861a538';
  $display->hide_title = PANELS_TITLE_FIXED;
  $display->title_pane = 'new-0eb1802a-9dce-47dd-b1f2-622c4d23f2ff';
  $mini->display = $display;

  $export['profile_mergedtab'] = $mini;


  /* enhanced contact main-tab */
  $mini = new stdClass();
  $mini->disabled = FALSE; /* Edit this to true to make a default mini disabled initially */
  $mini->api_version = 1;
  $mini->name = 'contact_view_main_tab_content';
  $mini->category = 'Mini panels';
  $mini->admin_title = 'ERPAL contact view main tab content';
  $mini->admin_description = '';
  $mini->requiredcontexts = array(
    0 => array(
      'identifier' => 'CRM Core Contact',
      'keyword' => 'crm_core_contact',
      'name' => 'entity:crm_core_contact',
      'entity_id' => '',
      'id' => 1,
    ),
  );
  $mini->contexts = array();
  $mini->relationships = array();
  $display = new panels_display();
  $display->layout = 'twocol';
  $display->layout_settings = array();
  $display->panel_settings = array(
    'style_settings' => array(
      'default' => NULL,
      'left' => NULL,
      'right' => NULL,
    ),
  );
  $display->cache = array();
  $display->title = 'Contact';
  $display->uuid = '4619cdc3-6122-4f78-aa67-cf40a463c9ee';
  $display->content = array();
  $display->panels = array();
  $pane = new stdClass();
  $pane->pid = 'new-0036f131-1490-4757-8e9e-da550fafdcbe';
  $pane->panel = 'left';
  $pane->type = 'entity_view';
  $pane->subtype = 'crm_core_contact';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'view_mode' => 'full',
    'context' => 'requiredcontext_entity:crm_core_contact_1',
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = '0036f131-1490-4757-8e9e-da550fafdcbe';
  $display->content['new-0036f131-1490-4757-8e9e-da550fafdcbe'] = $pane;
  $display->panels['left'][0] = 'new-0036f131-1490-4757-8e9e-da550fafdcbe';
  $pane = new stdClass();
  $pane->pid = 'new-f0049a02-8f6d-4ed4-bcdf-a2b61c84b19f';
  $pane->panel = 'right';
  $pane->type = 'views_panes';
  $pane->subtype = 'erpal_crm_activities-panel_pane_4';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array();
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = 'f0049a02-8f6d-4ed4-bcdf-a2b61c84b19f';
  $display->content['new-f0049a02-8f6d-4ed4-bcdf-a2b61c84b19f'] = $pane;
  $display->panels['right'][0] = 'new-f0049a02-8f6d-4ed4-bcdf-a2b61c84b19f';
  $pane = new stdClass();
  $pane->pid = 'new-3fe3c76d-a88e-4fbf-a8f8-586ae192f6d6';
  $pane->panel = 'right';
  $pane->type = 'views_panes';
  $pane->subtype = 'erpal_crm_contact_relationships-panel_pane_2';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array();
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 1;
  $pane->locks = array();
  $pane->uuid = '3fe3c76d-a88e-4fbf-a8f8-586ae192f6d6';
  $display->content['new-3fe3c76d-a88e-4fbf-a8f8-586ae192f6d6'] = $pane;
  $display->panels['right'][1] = 'new-3fe3c76d-a88e-4fbf-a8f8-586ae192f6d6';
  $pane = new stdClass();
  $pane->pid = 'new-8d7e4a7c-2f1b-4785-b5ef-e9800954a129';
  $pane->panel = 'right';
  $pane->type = 'views_panes';
  $pane->subtype = 'erpal_quote-panel_pane_4';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'context' => array(
      0 => 'requiredcontext_entity:crm_core_contact_1',
    ),
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 2;
  $pane->locks = array();
  $pane->uuid = '8d7e4a7c-2f1b-4785-b5ef-e9800954a129';
  $display->content['new-8d7e4a7c-2f1b-4785-b5ef-e9800954a129'] = $pane;
  $display->panels['right'][2] = 'new-8d7e4a7c-2f1b-4785-b5ef-e9800954a129';
  $pane = new stdClass();
  $pane->pid = 'new-4e00aec1-b0c6-48d9-a54a-82b1e71fc703';
  $pane->panel = 'right';
  $pane->type = 'views_panes';
  $pane->subtype = 'erpal_order-panel_pane_7';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'context' => array(
      0 => 'requiredcontext_entity:crm_core_contact_1',
    ),
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 3;
  $pane->locks = array();
  $pane->uuid = '4e00aec1-b0c6-48d9-a54a-82b1e71fc703';
  $display->content['new-4e00aec1-b0c6-48d9-a54a-82b1e71fc703'] = $pane;
  $display->panels['right'][3] = 'new-4e00aec1-b0c6-48d9-a54a-82b1e71fc703';
  $pane = new stdClass();
  $pane->pid = 'new-8e2fbc0c-bc76-40d6-b1cd-a63afb52e68d';
  $pane->panel = 'right';
  $pane->type = 'views_panes';
  $pane->subtype = 'erpal_invoice-panel_pane_2';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'context' => array(
      0 => 'requiredcontext_entity:crm_core_contact_1',
    ),
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 4;
  $pane->locks = array();
  $pane->uuid = '8e2fbc0c-bc76-40d6-b1cd-a63afb52e68d';
  $display->content['new-8e2fbc0c-bc76-40d6-b1cd-a63afb52e68d'] = $pane;
  $display->panels['right'][4] = 'new-8e2fbc0c-bc76-40d6-b1cd-a63afb52e68d';
  $display->hide_title = PANELS_TITLE_FIXED;
  $display->title_pane = '0';
  $mini->display = $display;

  $export['profile_maintab'] = $mini;


  /* anonymous user login (mini-) panel */
  $mini = new stdClass();
  $mini->disabled = FALSE; /* Edit this to true to make a default mini disabled initially */
  $mini->api_version = 1;
  $mini->name = 'erpal_anonymous_user_panel';
  $mini->category = '';
  $mini->admin_title = 'ERPAL anonymous user panel';
  $mini->admin_description = '';
  $mini->requiredcontexts = array();
  $mini->contexts = array();
  $mini->relationships = array();
  $display = new panels_display();
  $display->layout = 'erpaldropdownregion';
  $display->layout_settings = array();
  $display->panel_settings = array(
    'style_settings' => array(
      'default' => NULL,
      'content' => NULL,
      'trigger' => NULL,
      'dropdown' => NULL,
    ),
  );
  $display->cache = array();
  $display->title = '';
  $display->uuid = 'c7a9cefb-6663-4c1a-b132-f8073c9b59d3';
  $display->content = array();
  $display->panels = array();
  $pane = new stdClass();
  $pane->pid = 'new-dbfddf4e-a11e-43fa-8ac4-a4be293b6bc1';
  $pane->panel = 'dropdown';
  $pane->type = 'block';
  $pane->subtype = 'user-login';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = 'dbfddf4e-a11e-43fa-8ac4-a4be293b6bc1';
  $display->content['new-dbfddf4e-a11e-43fa-8ac4-a4be293b6bc1'] = $pane;
  $display->panels['dropdown'][0] = 'new-dbfddf4e-a11e-43fa-8ac4-a4be293b6bc1';
  $pane = new stdClass();
  $pane->pid = 'new-76d86e82-c2cf-4b5f-84cf-cf15b0052126';
  $pane->panel = 'trigger';
  $pane->type = 'custom';
  $pane->subtype = 'custom';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'admin_title' => '',
    'title' => '',
    'body' => '<a href="user" class="login">Login</a>',
    'format' => 'full_html',
    'substitute' => TRUE,
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $pane->uuid = '76d86e82-c2cf-4b5f-84cf-cf15b0052126';
  $display->content['new-76d86e82-c2cf-4b5f-84cf-cf15b0052126'] = $pane;
  $display->panels['trigger'][0] = 'new-76d86e82-c2cf-4b5f-84cf-cf15b0052126';
  $display->hide_title = PANELS_TITLE_FIXED;
  $display->title_pane = '0';
  $mini->display = $display;

  $export['anonymous_login_panel'] = $mini;


  return $export;
}

/**
 * Implements hook_image_default_styles().
 */
function erpal_layout_image_default_styles() {
  $styles = array();

  $styles['usermenu_profileimage'] = array(
    'label' => 'Usermenu Profileimage',
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 30,
          'height' => 30,
          'upscale' => 1,
        ),
        'weight' => 0,
      ),
    ),
  );

  return $styles;
}